<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\SubSubKelompokBarang;

class SubSubKelompokBarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataSubSubKelompokBarang = [
            [
                'id' => 204020711,
                'subkelompokbarang_id' => 2040207,
                'nama' => 'Perkakas Bengkel Kerja (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 204030818,
                'subkelompokbarang_id' => 2040308,
                'nama' => 'Stopwatch',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 204031002,
                'subkelompokbarang_id' => 2040310,
                'nama' => 'Timbangan Duduk',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010201,
                'subkelompokbarang_id' => 2060102,
                'nama' => 'Mesin Hitung Manual',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010207,
                'subkelompokbarang_id' => 2060102,
                'nama' => 'Mesin Kas Register',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010401,
                'subkelompokbarang_id' => 2060104,
                'nama' => 'Lemari Besi\/Metal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010404,
                'subkelompokbarang_id' => 2060104,
                'nama' => 'Filling Besi\/Metal',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010406,
                'subkelompokbarang_id' => 2060104,
                'nama' => 'Brankas Besar',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010412,
                'subkelompokbarang_id' => 2060104,
                'nama' => 'Lemari Kaca',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010414,
                'subkelompokbarang_id' => 2060104,
                'nama' => 'Alat Penyimpanan Perlengkapan Kantor (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010501,
                'subkelompokbarang_id' => 2060105,
                'nama' => 'Papan Visualisasi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010508,
                'subkelompokbarang_id' => 2060105,
                'nama' => 'Papan Tulis (Black Board)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010510,
                'subkelompokbarang_id' => 2060105,
                'nama' => 'Papan Tulis (White Board)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206010527,
                'subkelompokbarang_id' => 2060105,
                'nama' => 'Alat Pencetak Label',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020104,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Meja Kayu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020106,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Kursi Kayu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020108,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Tempat Tidur Besi\/Metal (Lengkap)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020111,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Meja Tulis',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020117,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Meja Resepsionis',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020119,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Meja Panjang',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020128,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Kursi Tamu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020130,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Kursi Putar',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020134,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Kursi Lipat',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020137,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Meja Komputer',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020148,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Meja 1\/2 Biro',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020161,
                'subkelompokbarang_id' => 2060201,
                'nama' => 'Lain-Lain',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020203,
                'subkelompokbarang_id' => 2060202,
                'nama' => 'Jam Elektronik',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020403,
                'subkelompokbarang_id' => 2060204,
                'nama' => 'AC Unit',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020603,
                'subkelompokbarang_id' => 2060206,
                'nama' => 'Televisi',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020607,
                'subkelompokbarang_id' => 2060206,
                'nama' => 'Loudspeaker',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020628,
                'subkelompokbarang_id' => 2060206,
                'nama' => 'Lambang Garuda Pancasila',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020629,
                'subkelompokbarang_id' => 2060206,
                'nama' => 'Gambar Presiden\/Wakil Presiden',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020639,
                'subkelompokbarang_id' => 2060206,
                'nama' => 'Dispenser',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206020650,
                'subkelompokbarang_id' => 2060206,
                'nama' => 'Alat Rumah Tangga Lainnya (Home Use) (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030201,
                'subkelompokbarang_id' => 2060302,
                'nama' => 'PC Unit',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030202,
                'subkelompokbarang_id' => 2060302,
                'nama' => 'Laptop',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030203,
                'subkelompokbarang_id' => 2060302,
                'nama' => 'Notebook',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030205,
                'subkelompokbarang_id' => 2060302,
                'nama' => 'Personal Komputer (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030306,
                'subkelompokbarang_id' => 2060303,
                'nama' => 'CPU',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030408,
                'subkelompokbarang_id' => 2060304,
                'nama' => 'Printer',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030414,
                'subkelompokbarang_id' => 2060304,
                'nama' => 'Keyboard',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030502,
                'subkelompokbarang_id' => 2060305,
                'nama' => 'Monitor',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030510,
                'subkelompokbarang_id' => 2060305,
                'nama' => 'Peralatan Personal Komputer (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030601,
                'subkelompokbarang_id' => 2060306,
                'nama' => 'Server',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030603,
                'subkelompokbarang_id' => 2060306,
                'nama' => 'Switch (Hub)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206030606,
                'subkelompokbarang_id' => 2060306,
                'nama' => 'Peralatan Jaringan (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206040109,
                'subkelompokbarang_id' => 2060401,
                'nama' => 'Meja dan Kursi Kerja\/Rapat Pejabat (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206040211,
                'subkelompokbarang_id' => 2060402,
                'nama' => 'Meja Tamu Biasa',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206040706,
                'subkelompokbarang_id' => 2060407,
                'nama' => 'Lemari Arsip',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 206040707,
                'subkelompokbarang_id' => 2060407,
                'nama' => 'Buffet Kayu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 207010101,
                'subkelompokbarang_id' => 2070101,
                'nama' => 'Kamera',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 207010112,
                'subkelompokbarang_id' => 2070101,
                'nama' => 'Audio Monitor Aktif',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 207010258,
                'subkelompokbarang_id' => 2070102,
                'nama' => 'LCD Projector',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 207020109,
                'subkelompokbarang_id' => 2070201,
                'nama' => 'Telepon PABX',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 207020111,
                'subkelompokbarang_id' => 2070201,
                'nama' => 'Pesawat Telepon',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 207020120,
                'subkelompokbarang_id' => 2070201,
                'nama' => 'Handphone',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 209010107,
                'subkelompokbarang_id' => 2090101,
                'nama' => 'Timbangan Elektornik',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 209010404,
                'subkelompokbarang_id' => 2090104,
                'nama' => 'Water Level Meter',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 209010464,
                'subkelompokbarang_id' => 2090104,
                'nama' => 'Alat Pemadam Kebakaran',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 518010402,
                'subkelompokbarang_id' => 5180104,
                'nama' => 'Alat-Alat Volley',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 518010405,
                'subkelompokbarang_id' => 5180104,
                'nama' => 'Alat-Alat Sepak Bola',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 518010407,
                'subkelompokbarang_id' => 5180104,
                'nama' => 'Alat Olah Raga (Lain-Lain)',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];
        for ($i = 0; $i < count($dataSubSubKelompokBarang); $i++) {
            $subSubKelompokBarang = SubSubKelompokBarang::create(
                $dataSubSubKelompokBarang[$i]
            );
        }
    }
}
